# Generated by Django 2.0.3 on 2018-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='target_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='收到公告的组织或用户'),
        ),
    ]
