# Generated by Django 3.0.2 on 2020-01-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_board_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='target_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='收到公告的组织或用户(发给所有人时, 该字段不生效)'),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.IntegerField(choices=[(0, '发给所有人'), (1, '发给某个组织'), (2, '发给某个人')], verbose_name='公告类型'),
        ),
    ]
