# Generated by Django 2.0.3 on 2018-03-15 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='机构名称')),
                ('code', models.IntegerField(default=0, verbose_name='编码')),
                ('org_type', models.PositiveSmallIntegerField(choices=[(1, '科室'), (2, '班组'), (3, '对组')], verbose_name='机构类型')),
                ('category_type', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], verbose_name='层级')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orgs.OrgProfile', verbose_name='机构上级')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
    ]
